apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ya316h37u-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ya316h37u-dotnet-basic-gitops